version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: docker build
          command: docker build -t new-client-announce .

workflows:
  install_and_configure_cli:
    jobs:
      - build
