version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.2.1
  node: circleci/node@5.2.0

commands:
  gcloud-authentication:
    steps:
      - gcp-cli/setup:
          gcloud_service_key: GCLOUD_SERVICE_KEY
          google_project_id: GOOGLE_PROJECT_ID

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: docker build
          command: docker build -t new-client-announce .
      - gcloud-authentication
      - run:
          name: gcloud configure
          command: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - run:
          name: docker push
          command: |
            docker tag new-client-announce asia-northeast1-docker.pkg.dev/data-intelligence/new-client-announce
            docker push asia-northeast1-docker.pkg.dev/data-intelligence/server/new-client-announce

workflows:
  install_and_configure_cli:
    jobs:
      - build
