version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.2.1
  node: circleci/node@5.2.0

commands:
  gcloud-authentication:
    steps:
      - gcp-cli/setup:
          gcloud_service_key: GCLOUD_SERVICE_KEY
          google_project_id: GOOGLE_PROJECT_ID

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - gcloud-authentication
      - run:
          name: docker configure
          command: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - run:
          name: docker build
          command: docker build -t new-client-announce .
      - run:
          name: docker tag
          command: docker tag new-client-announce asia-northeast1-docker.pkg.dev/$GOOGLE_PROJECT_ID/new-client-announce/new-client-announce:latest
      - run:
          name: docker push
          command: docker push asia-northeast1-docker.pkg.dev/$GOOGLE_PROJECT_ID/new-client-announce/new-client-announce:latest

  deploy:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - gcloud-authentication
      - run:
          name: docker configure
          command: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - run:
          name: set variables
          command: |
            export SLACK_BOT_TOKEN=$(gcloud secrets versions access latest --secret NEW_CLIENT_ANNOUNCE_SLACK_BOT_TOKEN --project $GOOGLE_PROJECT_ID)
            echo $SLACK_BOT_TOKEN
      # - run:
      #   name: deploy slack bot
      #   command: |
      #     gcloud run deploy new-client-announce \
      #       --image=asia-northeast1-docker.pkg.dev/$GOOGLE_PROJECT_ID/new-client-announce/new-client-announce:latest \
      #       --platform=managed \
      #       --region=asia-northeast1 \
      #       --allow-unauthenticated
workflows:
  install_and_configure_cli:
    jobs:
      # - build
      - deploy
