version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: echo "Hello, CircleCI!"

workflows:
  install_and_configure_cli:
    jobs:
      - build
